# argocd/apps.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neatspend-frontend
  namespace: argocd
  annotations:
    # Track the FRONTEND image
    argocd-image-updater.argoproj.io/image-list: frontend=andreivlaicu/ns-frontend
    argocd-image-updater.argoproj.io/frontend.allow-tags: regexp:^main-\d+$
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest

    # Write updates back to Git
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    # Helm values to modify
    argocd-image-updater.argoproj.io/helm.image-name: image.repository
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/VlaicuAndrei454/ns-gitops.git
    targetRevision: main
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: neatspend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neatspend-backend
  namespace: argocd
  annotations:
    # Track the BACKEND image
    argocd-image-updater.argoproj.io/image-list: backend=andreivlaicu/ns-backend
    argocd-image-updater.argoproj.io/backend.allow-tags: regexp:^main-\d+$
    argocd-image-updater.argoproj.io/backend.update-strategy: latest

    # Write updates back to Git
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main

    # Helm values to modify
    argocd-image-updater.argoproj.io/helm.image-name: image.repository
    argocd-image-updater.argoproj.io/helm.image-tag: image.tag
spec:
  project: default
  source:
    repoURL: https://github.com/VlaicuAndrei454/ns-gitops.git
    targetRevision: main
    path: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: neatspend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
