apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neatspend-ingress
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # more specific path first
          - path: {{ .Values.ingress.apiPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.backendServiceName }}
                port:
                  number: {{ .Values.ingress.backendServicePort }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.frontendServiceName }}
                port:
                  number: {{ .Values.ingress.frontendServicePort }}

